### ISSUE TITLE
requset: Make API more restful

### ISSUE THREAD

**Issue by nidbCN** [aimerneige/rfid-barber#1]
1. replace `card/search` with querystring such as `card/?phone={phone}`, do not use verb in url;
2. add field `banlance` when create a new card, it will be useful;

**Comment by aimerneige** [comment]
> replace card/search with querystring such as card/?phone={phone}, do not use verb in url;

It is hard to implement. I am lazy to do it.

---

> add field banlance when create a new card, it will be useful

Yes, you are right. Will be in next commit.
